apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-efficiency-prediction
spec:
  replicas: 2
  selector:
    matchLabels:
      app: machine-efficiency-prediction
  template:
    metadata:
      labels:
        app: machine-efficiency-prediction
    spec:
      containers:
      - name: machine-efficiency-prediction
        image: muhammedrasin0/gitops-project:latest
        ports:
        - containerPort: 5002
