apiVersion: v1
kind: Service
metadata:
  name: machine-efficiency-prediction
spec:
  selector:
    app: machine-efficiency-prediction
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
  type: LoadBalancer